version: '3'

services:
  wordpress:
    build: .
    image: your-wordpress-image-name
    container_name: your-wordpress-container-name
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: your-db-user
      WORDPRESS_DB_PASSWORD: your-db-password
      WORDPRESS_DB_NAME: your-db-name
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: your-mysql-container-name
    restart: always
    environment:
      MYSQL_DATABASE: your-db-name
      MYSQL_USER: your-db-user
      MYSQL_PASSWORD: your-db-password
      MYSQL_ROOT_PASSWORD: your-root-password

  nginx:
    image: nginx:latest
    container_name: your-nginx-container-name
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - wordpress
